
package com.realdolmen.wsdl.option;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "OptionWebServiceService", targetNamespace = "http://option.domain.realdolmen.com/", wsdlLocation = "http://localhost:8080/fleet-ejb/OptionWebService?wsdl")
public class OptionWebServiceService
    extends Service
{

    private final static URL OPTIONWEBSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.realdolmen.wsdl.option.OptionWebServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.realdolmen.wsdl.option.OptionWebServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/fleet-ejb/OptionWebService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/fleet-ejb/OptionWebService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        OPTIONWEBSERVICESERVICE_WSDL_LOCATION = url;
    }

    public OptionWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OptionWebServiceService() {
        super(OPTIONWEBSERVICESERVICE_WSDL_LOCATION, new QName("http://option.domain.realdolmen.com/", "OptionWebServiceService"));
    }

    /**
     * 
     * @return
     *     returns OptionWebService
     */
    @WebEndpoint(name = "OptionWebServicePort")
    public OptionWebService getOptionWebServicePort() {
        return super.getPort(new QName("http://option.domain.realdolmen.com/", "OptionWebServicePort"), OptionWebService.class);
    }

}
