
package com.realdolmen.wsdl.option;

import java.math.BigDecimal;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "OptionWebService", targetNamespace = "http://option.domain.realdolmen.com/")
public interface OptionWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.realdolmen.wsdl.option.Option
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.FindByIdResponse")
    public Option findById(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.realdolmen.wsdl.option.Option>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findLowerThandPrice", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.FindLowerThandPrice")
    @ResponseWrapper(localName = "findLowerThandPriceResponse", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.FindLowerThandPriceResponse")
    public List<Option> findLowerThandPrice(
        @WebParam(name = "arg0", targetNamespace = "")
        BigDecimal arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.realdolmen.wsdl.option.Option
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByName", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.FindByName")
    @ResponseWrapper(localName = "findByNameResponse", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.FindByNameResponse")
    public Option findByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.realdolmen.wsdl.option.Option>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.FindAllResponse")
    public List<Option> findAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.realdolmen.wsdl.option.Option>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByType", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.FindByType")
    @ResponseWrapper(localName = "findByTypeResponse", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.FindByTypeResponse")
    public List<Option> findByType(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
