
package com.realdolmen.wsdl.option;

import java.math.BigDecimal;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "OptionWebService", targetNamespace = "http://option.domain.realdolmen.com/")
public interface OptionWebService {


    /**
     * 
     * @param price
     * @return
     *     returns java.util.List<com.realdolmen.wsdl.option.Option>
     */
    @WebMethod(action = "findOptionLowerThandPrice")
    @WebResult(name = "optionss", targetNamespace = "")
    @RequestWrapper(localName = "findOptionLowerThandPrice", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.FindOptionLowerThandPrice")
    @ResponseWrapper(localName = "findOptionLowerThandPriceResponse", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.FindOptionLowerThandPriceResponse")
    public List<Option> findOptionLowerThandPrice(
        @WebParam(name = "price", targetNamespace = "")
        BigDecimal price);

    /**
     * 
     * @param type
     * @return
     *     returns java.util.List<com.realdolmen.wsdl.option.Option>
     */
    @WebMethod(action = "findOptionByType")
    @WebResult(name = "options", targetNamespace = "")
    @RequestWrapper(localName = "findOptionByType", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.FindOptionByType")
    @ResponseWrapper(localName = "findOptionByTypeResponse", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.FindOptionByTypeResponse")
    public List<Option> findOptionByType(
        @WebParam(name = "type", targetNamespace = "")
        String type);

    /**
     * 
     * @param option
     */
    @WebMethod(action = "createOption")
    @RequestWrapper(localName = "createOption", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.CreateOption")
    @ResponseWrapper(localName = "createOptionResponse", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.CreateOptionResponse")
    public void createOption(
        @WebParam(name = "option", targetNamespace = "http://option.domain.realdolmen.com/")
        Option option);

    /**
     * 
     * @param name
     * @return
     *     returns java.util.List<com.realdolmen.wsdl.option.Option>
     */
    @WebMethod(action = "findOptionByName")
    @WebResult(name = "options", targetNamespace = "")
    @RequestWrapper(localName = "findOptionByName", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.FindOptionByName")
    @ResponseWrapper(localName = "findOptionByNameResponse", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.FindOptionByNameResponse")
    public List<Option> findOptionByName(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param id
     * @return
     *     returns com.realdolmen.wsdl.option.Option
     */
    @WebMethod(action = "findOptionById")
    @WebResult(name = "option", targetNamespace = "http://option.domain.realdolmen.com/")
    @RequestWrapper(localName = "findOptionById", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.FindOptionById")
    @ResponseWrapper(localName = "findOptionByIdResponse", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.FindOptionByIdResponse")
    public Option findOptionById(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @return
     *     returns java.util.List<com.realdolmen.wsdl.option.Option>
     */
    @WebMethod(action = "findAllOption")
    @WebResult(name = "options", targetNamespace = "")
    @RequestWrapper(localName = "findAllOption", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.FindAllOption")
    @ResponseWrapper(localName = "findAllOptionResponse", targetNamespace = "http://option.domain.realdolmen.com/", className = "com.realdolmen.wsdl.option.FindAllOptionResponse")
    public List<Option> findAllOption();

}
