
package com.realdolmen.wsdl.pack;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "PackWebService", targetNamespace = "http://pack.domain.realdolmen.com/")
public interface PackWebService {


    /**
     * 
     * @param pack
     * @return
     *     returns com.realdolmen.wsdl.pack.Pack
     */
    @WebMethod(action = "updatePack")
    @WebResult(name = "packs", targetNamespace = "")
    @RequestWrapper(localName = "updatePack", targetNamespace = "http://pack.domain.realdolmen.com/", className = "com.realdolmen.wsdl.pack.UpdatePack")
    @ResponseWrapper(localName = "updatePackResponse", targetNamespace = "http://pack.domain.realdolmen.com/", className = "com.realdolmen.wsdl.pack.UpdatePackResponse")
    public Pack updatePack(
        @WebParam(name = "pack", targetNamespace = "http://pack.domain.realdolmen.com/")
        Pack pack);

    /**
     * 
     * @param id
     * @return
     *     returns com.realdolmen.wsdl.pack.Pack
     */
    @WebMethod(action = "findPackById")
    @WebResult(name = "pack", targetNamespace = "http://pack.domain.realdolmen.com/")
    @RequestWrapper(localName = "findPackById", targetNamespace = "http://pack.domain.realdolmen.com/", className = "com.realdolmen.wsdl.pack.FindPackById")
    @ResponseWrapper(localName = "findPackByIdResponse", targetNamespace = "http://pack.domain.realdolmen.com/", className = "com.realdolmen.wsdl.pack.FindPackByIdResponse")
    public Pack findPackById(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @return
     *     returns java.util.List<com.realdolmen.wsdl.pack.Pack>
     */
    @WebMethod(action = "findAllPacks")
    @WebResult(name = "packs", targetNamespace = "")
    @RequestWrapper(localName = "findAllPacks", targetNamespace = "http://pack.domain.realdolmen.com/", className = "com.realdolmen.wsdl.pack.FindAllPacks")
    @ResponseWrapper(localName = "findAllPacksResponse", targetNamespace = "http://pack.domain.realdolmen.com/", className = "com.realdolmen.wsdl.pack.FindAllPacksResponse")
    public List<Pack> findAllPacks();

    /**
     * 
     * @param pack
     */
    @WebMethod(action = "createPack")
    @RequestWrapper(localName = "createPack", targetNamespace = "http://pack.domain.realdolmen.com/", className = "com.realdolmen.wsdl.pack.CreatePack")
    @ResponseWrapper(localName = "createPackResponse", targetNamespace = "http://pack.domain.realdolmen.com/", className = "com.realdolmen.wsdl.pack.CreatePackResponse")
    public void createPack(
        @WebParam(name = "pack", targetNamespace = "http://pack.domain.realdolmen.com/")
        Pack pack);

}
