
package com.realdolmen.service.carmodel;

import com.realdolmen.domain.carmodel.CarModel;
import com.realdolmen.domain.ws.carmodel.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CarModelWebService", targetNamespace = "http://carmodel.domain.realdolmen.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CarModelWebService {


    /**
     * 
     * @param brand
     * @return
     *     returns java.util.List<com.realdolmen.domain.carmodel.CarModel>
     */
    @WebMethod
    @WebResult(name = "carModels", targetNamespace = "")
    @RequestWrapper(localName = "carModels", targetNamespace = "http://carmodel.domain.realdolmen.com/", className = "com.realdolmen.domain.carmodel.CarModels")
    @ResponseWrapper(localName = "carModelsResponse", targetNamespace = "http://carmodel.domain.realdolmen.com/", className = "com.realdolmen.domain.carmodel.CarModelsResponse")
    public List<CarModel> carModels(
        @WebParam(name = "brand", targetNamespace = "")
        String brand);

}
