
package com.realdolmen.service.carmodel;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CarModelWebServiceService", targetNamespace = "http://carmodel.domain.realdolmen.com/", wsdlLocation = "http://localhost:8080/fleet-ejb/CarModelWebService?wsdl")
public class CarModelWebServiceService
    extends Service
{

    private final static URL CARMODELWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CARMODELWEBSERVICESERVICE_EXCEPTION;
    private final static QName CARMODELWEBSERVICESERVICE_QNAME = new QName("http://carmodel.domain.realdolmen.com/", "CarModelWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/fleet-ejb/CarModelWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARMODELWEBSERVICESERVICE_WSDL_LOCATION = url;
        CARMODELWEBSERVICESERVICE_EXCEPTION = e;
    }

    public CarModelWebServiceService() {
        super(__getWsdlLocation(), CARMODELWEBSERVICESERVICE_QNAME);
    }

    public CarModelWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARMODELWEBSERVICESERVICE_QNAME, features);
    }

    public CarModelWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, CARMODELWEBSERVICESERVICE_QNAME);
    }

    public CarModelWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARMODELWEBSERVICESERVICE_QNAME, features);
    }

    public CarModelWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarModelWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CarModelWebService
     */
    @WebEndpoint(name = "CarModelWebServicePort")
    public CarModelWebService getCarModelWebServicePort() {
        return super.getPort(new QName("http://carmodel.domain.realdolmen.com/", "CarModelWebServicePort"), CarModelWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarModelWebService
     */
    @WebEndpoint(name = "CarModelWebServicePort")
    public CarModelWebService getCarModelWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://carmodel.domain.realdolmen.com/", "CarModelWebServicePort"), CarModelWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARMODELWEBSERVICESERVICE_EXCEPTION!= null) {
            throw CARMODELWEBSERVICESERVICE_EXCEPTION;
        }
        return CARMODELWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
