
package com.realdolmen.wsdl.carmodel;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "CarModelWebServiceService", targetNamespace = "http://carmodel.domain.realdolmen.com/", wsdlLocation = "http://localhost:8080/fleet-ejb/CarModelWebService?wsdl")
public class CarModelWebServiceService
    extends Service
{

    private final static URL CARMODELWEBSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.realdolmen.wsdl.carmodel.CarModelWebServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.realdolmen.wsdl.carmodel.CarModelWebServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/fleet-ejb/CarModelWebService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/fleet-ejb/CarModelWebService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CARMODELWEBSERVICESERVICE_WSDL_LOCATION = url;
    }

    public CarModelWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarModelWebServiceService() {
        super(CARMODELWEBSERVICESERVICE_WSDL_LOCATION, new QName("http://carmodel.domain.realdolmen.com/", "CarModelWebServiceService"));
    }

    /**
     * 
     * @return
     *     returns CarModelWebService
     */
    @WebEndpoint(name = "CarModelWebServicePort")
    public CarModelWebService getCarModelWebServicePort() {
        return super.getPort(new QName("http://carmodel.domain.realdolmen.com/", "CarModelWebServicePort"), CarModelWebService.class);
    }

}
